import type { Categoria, Producto } from "./types";

/**
 * Datos de referencia. Se usan como catálogo real SOLO mientras no exista
 * un proyecto de Supabase conectado (ver lib/productos.ts). Una vez que
 * NEXT_PUBLIC_SUPABASE_URL esté seteada, este archivo deja de leerse en
 * runtime — queda como base para supabase/seed.sql.
 */
export const CATEGORIAS_SEED: Categoria[] = [
  { id: "cat-monopatin", slug: "monopatin", nombre: "Monopatines", orden: 1 },
  { id: "cat-moto", slug: "moto", nombre: "Motos Eléctricas", orden: 2 },
  { id: "cat-bici", slug: "bici", nombre: "Bicicletas Eléctricas", orden: 3 },
];

const cat = (slug: Categoria["slug"]) =>
  CATEGORIAS_SEED.find((c) => c.slug === slug)!;

export const PRODUCTOS_SEED: Producto[] = [
  {
    id: "prod-1",
    slug: "zaros-l8-max",
    nombre: "ZAROS L8 Max",
    categoria_id: "cat-monopatin",
    categoria: cat("monopatin"),
    etiqueta: "Más vendido",
    descripcion:
      "El equilibrio perfecto entre potencia y autonomía. Motor de 500W (600W pico), app Tuya, frenos a disco y asiento incluido.",
    precio_ars: 1236800,
    precio_usd: 980,
    specs: [
      { label: "Potencia motor", value: "500W" },
      { label: "Potencia máxima", value: "600W" },
      { label: "Velocidad máx.", value: "32 km/h" },
      { label: "Autonomía", value: "28 km" },
      { label: "Batería", value: "15.6 Ah" },
      { label: "Frenos", value: "Disco + EABS" },
      { label: "Carga máx.", value: "150 kg" },
    ],
    imagenes: [],
    publicado: true,
    orden: 1,
  },
  {
    id: "prod-2",
    slug: "zaros-x7-urban",
    nombre: "ZAROS X7 Urban",
    categoria_id: "cat-monopatin",
    categoria: cat("monopatin"),
    etiqueta: null,
    descripcion:
      "Liviano y plegable, ideal para el último tramo hasta el trabajo. Se guarda en cualquier rincón.",
    precio_ars: 890000,
    precio_usd: 710,
    specs: [
      { label: "Potencia motor", value: "350W" },
      { label: "Velocidad máx.", value: "25 km/h" },
      { label: "Autonomía", value: "22 km" },
      { label: "Batería", value: "10 Ah" },
      { label: "Frenos", value: "Disco trasero" },
      { label: "Carga máx.", value: "120 kg" },
    ],
    imagenes: [],
    publicado: true,
    orden: 2,
  },
  {
    id: "prod-3",
    slug: "zaros-pro-s9",
    nombre: "ZAROS Pro S9",
    categoria_id: "cat-monopatin",
    categoria: cat("monopatin"),
    etiqueta: "Premium",
    descripcion:
      "Máxima potencia para quienes no quieren límites. Doble suspensión y autonomía de 45 km.",
    precio_ars: 1780000,
    precio_usd: 1410,
    specs: [
      { label: "Potencia motor", value: "800W" },
      { label: "Potencia máxima", value: "1000W" },
      { label: "Velocidad máx.", value: "40 km/h" },
      { label: "Autonomía", value: "45 km" },
      { label: "Batería", value: "20 Ah" },
      { label: "Frenos", value: "Doble disco" },
      { label: "Carga máx.", value: "150 kg" },
    ],
    imagenes: [],
    publicado: false,
    orden: 3,
  },
  {
    id: "prod-4",
    slug: "zaros-volt-r1",
    nombre: "ZAROS Volt R1",
    categoria_id: "cat-moto",
    categoria: cat("moto"),
    etiqueta: "Top",
    descripcion:
      "Una moto eléctrica de verdad: 2000W, 65 km/h y 80 km de autonomía. Patente no requerida según normativa local.",
    precio_ars: 3450000,
    precio_usd: 2740,
    specs: [
      { label: "Potencia motor", value: "2000W" },
      { label: "Potencia máxima", value: "3000W" },
      { label: "Velocidad máx.", value: "65 km/h" },
      { label: "Autonomía", value: "80 km" },
      { label: "Batería", value: "60V 32Ah" },
      { label: "Frenos", value: "Doble disco hidráulico" },
      { label: "Carga máx.", value: "180 kg" },
    ],
    imagenes: [],
    publicado: true,
    orden: 1,
  },
  {
    id: "prod-5",
    slug: "zaros-city-emoto",
    nombre: "ZAROS City E-Moto",
    categoria_id: "cat-moto",
    categoria: cat("moto"),
    etiqueta: null,
    descripcion:
      "Diseño urbano, asiento para dos y baúl. Pensada para moverte todo el día sin cargar.",
    precio_ars: 2980000,
    precio_usd: 2365,
    specs: [
      { label: "Potencia motor", value: "1500W" },
      { label: "Potencia máxima", value: "2000W" },
      { label: "Velocidad máx.", value: "55 km/h" },
      { label: "Autonomía", value: "70 km" },
      { label: "Batería", value: "60V 24Ah" },
      { label: "Frenos", value: "Disco delantero y trasero" },
      { label: "Carga máx.", value: "160 kg" },
    ],
    imagenes: [],
    publicado: true,
    orden: 2,
  },
  {
    id: "prod-6",
    slug: "zaros-eride-c3",
    nombre: "ZAROS eRide C3",
    categoria_id: "cat-bici",
    categoria: cat("bici"),
    etiqueta: null,
    descripcion:
      "Bici de ciudad con pedaleo asistido y 60 km de autonomía. Cambio Shimano y luces integradas.",
    precio_ars: 1120000,
    precio_usd: 890,
    specs: [
      { label: "Potencia motor", value: "250W" },
      { label: "Potencia máxima", value: "350W" },
      { label: "Velocidad máx.", value: "32 km/h" },
      { label: "Autonomía", value: "60 km" },
      { label: "Batería", value: "36V 12Ah" },
      { label: "Frenos", value: "Disco mecánico" },
      { label: "Carga máx.", value: "120 kg" },
    ],
    imagenes: [],
    publicado: true,
    orden: 1,
  },
  {
    id: "prod-7",
    slug: "zaros-trail-emtb",
    nombre: "ZAROS Trail E-MTB",
    categoria_id: "cat-bici",
    categoria: cat("bici"),
    etiqueta: "Aventura",
    descripcion:
      "Mountain bike eléctrica con suspensión completa. Para ciudad y montaña, hasta 90 km por carga.",
    precio_ars: 1690000,
    precio_usd: 1340,
    specs: [
      { label: "Potencia motor", value: "500W" },
      { label: "Potencia máxima", value: "750W" },
      { label: "Velocidad máx.", value: "40 km/h" },
      { label: "Autonomía", value: "90 km" },
      { label: "Batería", value: "48V 15Ah" },
      { label: "Frenos", value: "Disco hidráulico" },
      { label: "Carga máx.", value: "130 kg" },
    ],
    imagenes: [],
    publicado: true,
    orden: 2,
  },
  {
    id: "prod-8",
    slug: "zaros-urban-fold",
    nombre: "ZAROS Urban Fold",
    categoria_id: "cat-bici",
    categoria: cat("bici"),
    etiqueta: "Plegable",
    descripcion:
      "Bicicleta eléctrica plegable: entra en el baúl del auto o debajo del escritorio. Practicidad total.",
    precio_ars: 980000,
    precio_usd: 780,
    specs: [
      { label: "Potencia motor", value: "350W" },
      { label: "Potencia máxima", value: "500W" },
      { label: "Velocidad máx.", value: "28 km/h" },
      { label: "Autonomía", value: "50 km" },
      { label: "Batería", value: "36V 10Ah" },
      { label: "Frenos", value: "Disco mecánico" },
      { label: "Carga máx.", value: "110 kg" },
    ],
    imagenes: [],
    publicado: false,
    orden: 3,
  },
];
